CREATE TABLE FAVORITE_SONG (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    SONG_ID INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (SONG_ID) REFERENCES SONG(ID)
)

CREATE TABLE FAVORITE_ALBUM (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    ALBUM_ID INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID)
)

CREATE TABLE FAVORITE_ARTIST (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    ARTIST_ID INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES USERS(ID)
)

CREATE TABLE FAVORITE_REVIEW (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    REVIEW_ID INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(ID)
)