CREATE TABLE FAVORITE_SONG (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    SONG_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (SONG_ID) REFERENCES SONG(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)